# Docker Compose для локальной разработки

version: '3.8'

services:
  # Мини-приложение
  miniapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VITE_API_BASE_URL: http://remnawave_bot:8080
        VITE_BOT_USERNAME: "@your_bot"
        VITE_ENABLE_3D_EFFECTS: "true"
        VITE_ENABLE_PARTICLES: "true"
        VITE_APP_NAME: "VPN Subscription"
        VITE_DEFAULT_LANGUAGE: "ru"
    container_name: remnawave-miniapp
    restart: unless-stopped
    ports:
      - "${MINIAPP_PORT:-3001}:3000"
    environment:
      - NODE_ENV=production
    networks:
      - remnawave-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  # Подключаемся к существующей сети remnawave
  remnawave-network:
    external: true
    name: remnawave-network
